### ISSUE TITLE
Making a voice-activated news app using React, Alan Ai, and Strapi

### ISSUE THREAD

**Issue by christofa** [strapi/community-content#1001]
## Introduction
A news application is an interactive database that conveys a story preferably using software rather than words or images. It can assist each reader in understanding a story in a way that is individually significant to them by displaying data that is particular to them.

## Goals
After reading this article, readers will have a solid understanding of the Strapi tool, including how it benefits companies and developers, how safe it is, and how straightforward it is to use as we create an Alan-powered news application.

## Outline
- Why use Strapi?
- Breakdown of what we will be building
- Setting up our React file
    - Adding all related component files
    - Finishing up the frontend
- Deploying Strapi into our project
    - Content Structure
    - Connecting the CMS to the application
- Attaching the Alan Ai button to the project
    -  Adding commands to Alan Studio
    - Testing the Alan button
- Displaying all News Categories
    - Adding the Navigation feature
- Testing the Application
- Conclusion 

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@christofa can you give more details on what functionality be available using Alan Ai.  What will the application do, and what Strapi feature will it showcase?

**Comment by christofa** [comment]
@PaulBratslavsky Hi, News content will be stored in the strapi CMS and be displayed in our React project showing how easy and effective it is to store data with strapi. Then the Alan Ai helps to describe the application and navigate through the stored data opening any news requested for by the user which makes the application very accessible.

**Comment by PaulBratslavsky** [comment]
@christofa I like the idea of using Alan Ai but based on your description, you are just using it to read data, but what would make this post more enticing is to cover how to add data to strapi via voice-to-text.  We currently have a lot of articles that describe how to fetch data so would be great to talk about how to post data.  

Or possibly having a login page that can be logged in via voice.

Let me know if you have any other questions.  We are just trying to get more articles that cover more Strapi functionalities rather than just using it to store and fetch data.  Since a lot of that is already covered on our blog.

**Comment by christofa** [comment]
Hi @PaulBratslavsky thanks for the response. I can look into the features you mentioned. Thanks

**Comment by christofa** [comment]
Hi @PaulBratslavsky, you changed the labels. Should I start working on article?

**Comment by PaulBratslavsky** [comment]
Upon further review, for the time being we are looking for more intermediate to advanced topics around Strapi development and customizatin.
