### ISSUE TITLE
[SUBMIT] Users Workflow in Strapi

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1004]
**My resource**

Hello 👋 @dessireugarte and @PaulBratslavsky 

I'll like to work on this topic,  below is my outline for the article.

### users roles and permissions
###Adding new users

- Super admin
-  Editor
- Author

### Workflow(using content publications for demonstration)
- Content creation (Author)
- Content editing and formatting (editor)
- Content publishing (super admin)
### Conclusion 

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by noblefresh** [comment]
Hello, I will like to work on this topic. Can it be assigned to me?

**Comment by popoolatopzy** [comment]
Sorry @noblefresh, I've already put in for this article

**Comment by popoolatopzy** [comment]
Hi @PaulBratslavsky 
I am trying to research on Strapi console but I could not find how to open the Strapi console on my terminal.

**Comment by shammadahmed** [comment]
@popoolatopzy You can install the Strapi CLI on your terminal with npm or yarn. 

In case you leave the topic, I want to have it.

**Comment by PaulBratslavsky** [comment]
Lets create a separate issue for this topic.  I am closing this one for now.  Since we already have a similar article around user workflow.  https://strapi.io/blog/strapi-s-user-roles-and-permissions-for-admin-panel-1

@popoolatopzy you will need to have strapi project installed and you would run `yarn strapi console`. 

Check out the above linked video in previous comment.  If you have questions, you can ask in the write for the community channel.  Or if you want to choose another topic, you can let  shammadahmed have a go on this one.

For not I will close this issue.

**Comment by shammadahmed** [comment]
@popoolatopzy Could you please confirm if you have left the topic? I want to write it.

**Comment by popoolatopzy** [comment]
@shammadahmed  I'm not working on the topic, you can take it

**Comment by shammadahmed** [comment]
@popoolatopzy Thanks.
