### ISSUE TITLE
Creating a REST API with Strapi

### ISSUE THREAD

**Issue by Bilal7168** [strapi/community-content#1007]
This is a simple article that will demonstrate how to host a simple REST API endpoint for retrieving and sending data. This can be of great help to users who are building an application and want to use REST for data management. This will also point out how easy it is for them to do so using Strapi.

Outline
Introduction
Pre-Requisites
Installing Node.js
Installing Yarn
Boot up Strapi at localhost
Creating REST API data items
Testing and Usage
Conclusion

-->

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@Bilal7168 Thank you for your submission, but we currently have plenty of examples on our blog where we showcase Strapi as an API. 

At the moment, we are looking for more intermediate/advanced articles. Some topics include "How to populate deeply nested data on the front end" or how to set up and use this populate plugin. https://market.strapi.io/plugins/strapi-plugin-populate-deep. 

For now, I will close this issue. 

We are currently not accepting any new article submissions until January due to having many articles in the queue.
