### ISSUE TITLE
[SUBMIT] Single type vs collection type

### ISSUE THREAD

**Issue by oyedeletemitope** [strapi/community-content#1110]
single types and collection types are two important features of Strapi that allow developers to easily manage and expose their content through a RESTful API.

In this article, we’ll take a look at both types, create an example for each and also state their differences.

Outline 

- introduction 
- Brief intro on strapi( including setting up)
- What are single type:This section will talk about what single types are in strapi and also create a single type example 
- What are collection types : this section will talk about what collection types are and also create an example.
- Differences between both
- When to use them
- Conclusion 

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by danielonugha0** [comment]
I would love to write on this topic @PaulBratslavsky @Mcastres

**Comment by oyedeletemitope** [comment]
@PaulBratslavsky @Mcastres

**Comment by PaulBratslavsky** [comment]
@oyedeletemitope apologize for the late response.  We have a backlog of articles in review, and due to limited bandwidth, we are taking longer than expected. 
 
After further review, we are looking for articles about best practices around customization, extension, and deployment. 

I will be closing this issue due to not being the right content at the moment.
