### ISSUE TITLE
[UPDATE OUTDATED CONTENT]

### ISSUE THREAD

**Issue by Shaggy1357** [strapi/community-content#1131]
**Description**

Hi Team,

I'm working on implementing social authentication providers in strapi but found that most of the information related to it that is mentioned in the document is outdated or does not follow the latest flow of the providers available in strapi. Hence it becomes very challenging to figure it out. 

So far I'm able to implement major providers like Facebook, Google, Linkedin and Discord but not able to find any relatable content for the rest on the internet or the strapi blogs and tutorials and got stuck in implementing with Twitter. 

Has anyone worked on this topic? Would be very helpfull if anyone has worked on it recently so that I can understand the flow.

Releasing updated tutorials and blogs would be very helpfull. 

thanks.

**Link of the content**

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by dessireugarte** [comment]
Hello @Shaggy1357!
Thanks for the suggestion. Currently, we have a tutorial that explains the [Strapi authentication flows with Facebook](https://strapi.io/blog/learning-strapi-authentication-flows-with-the-facebook-provider). 
We will add this to the content pipeline this tutorial idea and if we find an author interested, we will work on it. In the meantime, we will close the issue since the request made was not the correct one.
