### ISSUE TITLE
 How to Build a chat app with React, Strapi & Firebase[SUBMIT]

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#1261]
Building a chat app with React, Strapi, and Firebase involves combining frontend development with React, a backend using Strapi for managing the application's data, and Firebase for real-time communication.

Outline:
Setting up Strapi Backend
Setting up Firebase
User Authentication
Integrate Strapi with React
building the Chat Room
Read Chat Messages
Create New Messages
Testing our App
Conclusion

**Comment by hana75** [comment]
Hello @lucky4242,

Thanks for your submission. There's something interesting in demonstrating with React how to fetch data from Strapi, and displaying it dynamically in React components. I am also interested in how to integrate Firebase for user authentication and real-time updates. I think the article should focus on those two points, more than the use case in itself of building a chat app.
Could you use Next.js instead of React for this article?

Small feedbacks:
- Setting up Strapi Backend -> Here you can just add a line to redirect to existing Quickstart guides.
- Setting up Firebase: Use your personal experience to discuss the advantages of using Firebase for real-time data syncing, authentication, and hosting.

If the feedbacks are OK with you, you can start working on that article.

**Comment by lucky4242** [comment]
Hi @hana75 
Ok working on it

**Comment by vcoisne** [comment]
@lucky4242 did you get a chance to write a draft ?

**Comment by lucky4242** [comment]
Yes but still on it. I should be done by the end of this week.

**Comment by vcoisne** [comment]
Thats great to hear @lucky4242 !

**Comment by lucky4242** [comment]
@vcoisne sorry for the delay. Here is the link to the draft:
 
https://www.dropbox.com/scl/fi/6fd7g2mpu7lk0fzrmtgnw/How-to-Build-a-Chat-App-with-React-Strapi-Firebase.paper?rlkey=p7kgp666q0xc19iv6tfmzjsb9&dl=0

**Comment by vcoisne** [comment]
Thank you @lucky4242 we'll start reviewing this week.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @lucky4242 ,

I trust you are doing great!

I was having a hard time running and testing your application. It doesn't seem to work as expected. Also, I have left out some comments for you to review.

Aside that, your content is good. Once the issues have been fixed I'd be happy to publish this article.

Also, please feel free to let me know if you have any questions.

**Comment by lucky4242** [comment]
Hi @Theodore
Done with the comments. I think the reason you are having a hard time running the app is because of the Firebase console. You have to input your own Google authentication details.

**Comment by lucky4242** [comment]
Hi @theodore
I just removed a series of repetitions in my work. Check out thanks. 

https://www.dropbox.com/scl/fi/6fd7g2mpu7lk0fzrmtgnw/How-to-Build-a-Chat-App-with-React-Strapi-Firebase.paper?rlkey=p7kgp666q0xc19iv6tfmzjsb9&dl=0

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @lucky4242 ,

I left some comments in your draft. Please do check it out. Thanks.
