### ISSUE TITLE
[Partner Stream Topic CFP] Using GraphQL with Strapi and customizing it to your needs

### ISSUE THREAD

**Issue by ls-ramos** [strapi/community-content#1272]
**My Request**
Hello 👋 , below you can find my request.

#### Description: 
The idea of this talk is to show how to start using GraphQL with Strapi. First, we will present what are the initial setups needed to use the generated Schema and continue by showing a possible way to customize the schema generated, customize existing resolvers, or create new ones. The final goal will be to help the listener feel confident using GraphQL together with Strapi, as well as feel ready to modify the API to the specific needs the user might have.

#### Outline:
- GraphQL with Strapi initial setup
- Securing GraphQL API with API token
- Scheme customization
- Resolver creation and customization 

Let me know what you think @paulbratslavsky :)

Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @ls-ramos,

Thank you for your interest! We already have articles related to GraphQL.

Due to the high volume of submissions, we're currently pausing new article submissions. However, we'd love for you to explore the existing articles labeled "Looking for Author" and choose one that interests you.
