### ISSUE TITLE
Building FlutterGigs with Strapi and Nuxt

### ISSUE THREAD

**Issue by Ethiel97** [strapi/community-content#1292]
**The concerning content**

This post is to explain how I use Strapi and Nuxt to build my project FlutterGigs. I'll focus on essential aspects like:
* authentication;
* data fetching using REST APIs;
* state management, etc

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Ethiel97,

Thank you for submitting your article idea. Could you please provide more details about FlutterGigs since we already have articles on Nuxt?

Also, considering you will be implementing authentication, would you be interested in addressing issue #1291? Let me know if you are interested :)

**Comment by Ethiel97** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku !
Saw the issue had been addressed.

In my post I'd like to talk about how data is fetched from Strapi and converted to a Nuxt State in Pinia and and dispatched through components.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Ethiel97 ,

We already have internal blog posts on the way that is based on Nuxt. Please feel free to submit any other article idea or select from the requested contents. I will close this issue. Thanks.
