### ISSUE TITLE
[TOPIC] Build the same strapi-starter-next-corporate for Nuxt/Vue.JS?

### ISSUE THREAD

**Issue by biapar** [strapi/community-content#167]
Is possible to build the same strapi-starter-next-corporate example for Nuxt/Vue.JS?

**Comment by Mcastres** [comment]
Hello @biapar, me and @remi2j are currently working on a Gridsome Portfolio and a Nuxt.js E-commerce starter.
We want first to provide different type of website before iterating on the stack. 

We are looking for people who might be interested by reproducing starter but with their favorite stack

**Comment by biapar** [comment]
I wish to build a website for a customer with strapi backend and nuxt.js frontend. How to help you?

**Comment by remi2j** [comment]
If it's for a corporate site, I would recommend that you look into our [Next starter](https://github.com/strapi/strapi-starter-next-corporate). You'll see how we structure the data on Strapi, and how to render a dynamic zone on the frontend.

To translate it to a Nuxt app, you can use the [Strapi module for Nuxt](https://strapi.nuxtjs.org/) to query your data, instead of making API calls directly.

**Comment by elhe26** [comment]
Hi @remidej. Any updates regarding this topic? our company is going to rebuild the corporate site using nuxt + strapi and we want to know if you guys have this template before we start looking into your Next starter.

**Comment by remidej** [comment]
Hey @elhe26 

We have no short-term plan for a Vue corporate starter, so don't let this hold you back.

But you can still create a Strapi backend that's set up for a corporate site:

```sh
# Using Yarn
yarn create strapi-app my-site --template https://github.com/strapi/strapi-template-corporate

# Or using NPM
npx create-strapi-app my-site --template https://github.com/strapi/strapi-template-corporate
```
