### ISSUE TITLE
[TOPIC]Strapi deployment on AWS

### ISSUE THREAD

**Issue by pakwai122** [strapi/community-content#241]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!
The official doc didn't work so well I think. For instance iam role policy/security group didn't add the port for connecting RDS DB, etc.
https://strapi.io/documentation/v3.x/deployment/amazon-aws.html

Therefore, I'm looking for a video that shows how to deploy it to AWS with 
EC2(strapi), RDS(database)/S3(static images).
Dealing with SSL with  Let's Encrypt via automated tools like certbot(either provided dns domain name or custom domain name in route53)

installing nginx with preset config?
https://www.digitalocean.com/community/tools/nginx

Source control with GitHub or any others
Auto scaling, load balancing, distributed or centralized deployment?

This is good approach to split it into dev/staging/ production for project management, but outdated.
https://github.com/61FINTECH/deploy-strapi-on-aws
It would be great if some strapi experts can do it for community.

**Comment by MattieBelt** [comment]
I'm not an expert on AWS, so wouldn't be the right person to write something in depth. 
But I would like point out that I have done an update on the AWS deploy docs regarding the upload config, checkout strapi/strapi#8223.

**Comment by samuelarogbonlo** [comment]
I have relevant experience with GCP and may be able to apply that knowledge to work on this. Thanks

**Comment by purnimagupta** [comment]
@samuelarogbonlo Have you started to work on it? If you haven't, I would like to write a tutorial for it. Let me know.

**Comment by samuelarogbonlo** [comment]
@purnimagupta You can go ahead.

**Comment by purnimagupta** [comment]
@malgamves I'm interested in writing this topic. Shall I go ahead with it?

**Comment by purnimagupta** [comment]
@malgamves I'm waiting for your reply. Please let me know.

**Comment by Mcastres** [comment]
Hey @purnimagupta, are you not working on another topic? If not then I'll can assign you on this one.

**Comment by purnimagupta** [comment]
@Mcastres I was working on this topic https://github.com/strapi/community-content/issues/218. It is done, unless there are any review comments to address.

So meanwhile I thought of working on this one. Video is fine with me, although it will be my first time. Any tools that you recommend?

**Comment by Mcastres** [comment]
I'll review it during the week. Ok then you can start to work on this one :)
Maybe you can use OBS for recording your computer ! Great tool

**Comment by purnimagupta** [comment]
@Mcastres, I'm following Strapi AWS [guide](https://strapi.io/documentation/developer-docs/latest/deployment/amazon-aws.html). Have few questions regarding it. 

The doc mentions that the steps are similar for all the databases(Postgres, MySQL, MongoDB, PostgreSQL, MariaDB, SQLite) which Strapi supports. 

But RDS is a relational database and doesn't support MongoDB. So does this mean that this tutorial is only applicable to Relational Databases that Strapi supports?

For MongoDB, people will have to use MongoDB Atlas?

Should I only be focusing on relational databases while working on this topic?

**Comment by malgamves** [comment]
May @derrickmehaffy can offer some clarity here.

**Comment by derrickmehaffy** [comment]
The AWS documentation needs to be refactored.

@purnimagupta we do only support MongoDB directly and not AWS's DocumentDB (or any cloud proprietary database such as AWS Aurora, and I think Azure has a few as well).

Due to MongoDB's new license system, cloud providers are not allowed to offer a managed version of MongoDB so you would need to use Atlas (as that is MongoDB's own cloud managed database service).

**Comment by purnimagupta** [comment]
@derrickmehaffy 

Okay. As I understand it, if someone wants a self-managed MongoDB they will have to use MongoDB Atlas. Is that correct?

So does AWS offers any service for MongoDB which is not self-managed and if needed, can be used as an alternative to MongoDB Atlas? I'm asking this so that I could clear this confusion in my video which many readers may have.

Also, what does the refactoring involve? I can probably avoid showing that section in the video until it is refactored.

**Comment by derrickmehaffy** [comment]
You can easily run a self managed database on an EC2 instance.

If you want my recommendation though, skip Mongo entirely and go with either self managed PistgreSQL or AWS RDS.

(Refactoring is needed all over, it just hasn't been reviewed and the current step breakdown is just too complex or easy to follow)

**Comment by purnimagupta** [comment]
@Mcastres 

Strapi is deployed to AWS EC2. I have used Strapi S3 provider and AWS RDS Service as requested in Github issue.
I can see that images are uploaded in S3 bucket, and I can also see collection being created into my AWS RDS postgresql database
10:53
Now, I can also try adding custom domain to it via Route53. I already have my website running on namecheap servers and I can connect it with AWS Route53. Do you think that will suffice?Since I can't buy a SSL certificate which AWS offers since it's very very expensive for me. I'm not in my free tier as well. (edited) 
10:58
Do you think that is this enough of a content to make a video?
Or I should also demonstrate how to set up Ngnix? I haven't used it before so I'll have to spend some time reading about it. Let me know your thoughts.

**Comment by Mcastres** [comment]
Hey @purnimagupta !

Yes it will certainly be enough content to make a video!
But installing Strapi on a EC2 requires to set up NGINX in the process no?

However, it would be interesting to demonstrate this process IMO.

**Comment by purnimagupta** [comment]
@Mcastres I don't think so that one would need to set up Ngnix if they just want to deploy the app.

Though, I haven't used it before. IMO, either Ngnix/AWS Elastic Load Balancer could be used to distribute the incoming application traffic to multiple EC2 instances that are running. So request would come via load balancers/Ngnix instead of EC2.

And to set up a custom domain name to your EC2 URL, you can either use Ngnix service or AWS Route 53. 

If you want, I can demonstrate how to link an existing domain name with Route53.

 For ex: My root domain is www.purnimagupta.com which is running on NameCheap servers. I can create a subdomain in Route53 and link it with Namecheap and point to the running EC2 instance? 
 
 Let me know if that make sense?

**Comment by Mcastres** [comment]
> If you want, I can demonstrate how to link an existing domain name with Route53.

Alright, that would be great then!
That's sounds good to me :)

**Comment by derrickmehaffy** [comment]
> I don't think so that one would need to set up Ngnix if they just want to deploy the app to EC2.

You will if you want SSL, we don't handle SSL natively in Strapi and to properly run SSL the application would need to bind on Port 443, which unless ELB can remap ports (forget off the top of my head) it's not a good idea to run a node application as root, which is required on any port below 1024 in Linux.

Subdomains you might be able to bypass the Nginx requirement if the ELB can handle the port mapping and binding with an SSL certificate, though it would require a cert from AWS to do so. If the user is planning to use Let's Encrypt for a free cert than you will hit problems without a proxy layer.

Likewise if the user is planning to do any sub-path proxying you will need a proxy layer that can do some rewriting rules as we mention in the documentation:

Sub-folder unified: https://strapi.io/documentation/developer-docs/latest/deployment/nginx-proxy.html#sub-folder-unified
Sub-folder split: https://strapi.io/documentation/developer-docs/latest/deployment/nginx-proxy.html#sub-folder-split

Specifically the rewrite rules: `rewrite ^/api/(.*)$ /$1 break;`

**Comment by ShadaW11** [comment]
Heyyy @purnimagupta Its been w while. Did you get a chance to start working on this topic?

**Comment by purnimagupta** [comment]
@ShadaW11, I had begun working on it and created a demo app which later I to AWS EC2. However, I incurred a lot of AWS charges (amounting to almost $200 USD). I stopped any further work (Route 53, SSL, etc) because the charges were getting exceedingly high.

Have asked @malgamves if I can have access to a Strapi-provided AWS account for this (because even if anyone else has a free tier it would only last for an year and they'd start incurring charges). Moreover, only T2.micro instance is available on the free tier plan, but [Strapi requires a minimum of T2.small](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html) so free-tier plan can't be used anyway. Due to this, it's been difficult to continue working on this article and make further progress.

In the meantime, I'm working on another [article](https://github.com/strapi/community-content/issues/87) -

**Comment by ShadaW11** [comment]
Hello @purnimagupta would you be interested in using @malgamves's AWS account to complete this tutorial? Otherwise we can close this issue if its not possible.

**Comment by derrickmehaffy** [comment]
@ShadaW11 It's best to just place this on hold and I plan to work with the documentation team after v4 release to refactor our existing documentation for AWS deployment. (This goes for all deployment guides, best to just wait til after v4)

**Comment by ShadaW11** [comment]
@derrickmehaffy thank you for the feedback

**Comment by PaulBratslavsky** [comment]
We currently have a similar article that is scheduled to be released. Closing.
