### ISSUE TITLE
Waiter Food Order taking to Restaurant POS with Strapi or any Jamstack framework

### ISSUE THREAD

**Issue by saum14** [strapi/community-content#261]
Looking for a insight into on How I can build a Project using HTML, JAVAscript, CSS only a Restaurant Dine in Table Order system Which Could do the Following :
1. The POS(Point of Sale ) app can Take Order, Print KOT (Kitchen Order Ticket) , Billing and Accept Payment
2. The Waiter (User as Waiter Role) - Can Take orders at the Table itself and that should refelect in the Main App for Billing 
3. Waiter could add or delete the items in the Order and it must sync with the Main App

**Comment by Mo9a7i** [comment]
You're looking into a system design in general, not an api related issue.

I would recommend you visit a development firm to document down your requirements, however, since you're here, and I'm here typing, I wouldnt waste your and my time for nothing.

You have multi sub systems within your system:
- a database
- api to be consumed by frontends (strapi can help with the above two)
- frontends
  - 1 for clients and waiters (menus and carts)
  - 1 for admin users (reporting and adding waiters and follow up with clients)
- payment system (to link with visa, debit, paypal, banks ...etc.
- kitchen ticketing system

As you can see, its not only one component and definitely, strapi cant help with all, its either you find a full-stack developer or buy an off shelve solution that fits your needs


However, for documenting your requirements, Take the below notes and questions into consideration:
- Customer would place an order and pay, then a ticket will be printed, this way, waiters and managers have no way of editing the request, your chefs will immediately, you can stop the printing of ticket and place the order into a pending queue, where waiters and managers can review and approve and then the payment is done, ticket printed, and customer notified about approval
- this way, if there was an issue, the waiter can walk to the table and confirm certain things with customer, replace or delete if needed, and confirm the order
- this way, you can also add the ability of physical payment by the waiter handing a swipe machine or taking cash and marking the order paid so the kitchen ticket is printer.


All the above will definitely require a database and api and on that, strapi can provide you a great solution for such use case as it makes db creation, management, editing, adding, deleting, and api creation a seamless experience instead of hard-coding and typing all aspects of the db+api

Hope that helps

**Comment by saum14** [comment]
Thanks for the insights... And your valuable time in writing the basic
steps .

I will try to connect with developer to discuss further
