### ISSUE TITLE
[SUBMIT] Automating Emails with Strapi CRON Jobs - Setting up Cron jobs in Strapi

### ISSUE THREAD

**Issue by oviecodes** [strapi/community-content#457]
**My Request**

Hello @ShadaW11 I would like to write an article that introduces users to cron jobs and how to set them up in Strapi

Outline:
Introduction to Strapi
Getting started with Strapi
A brief overview of Strapi applications
Introduction to cron jobs
Setting up Cron jobs in Strapi
Building an application that collects user emails and add them to our mailing list
Using Cron jobs to automate the sending of emails to users in our mailing list.
Conclusion.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by krofax** [comment]
Hello @ShadaW11 can i take this topic?

**Comment by ShadaW11** [comment]
Hey @oviecodes thank you for sending the outline. As mentioned in the email and on discord, we have paused the tutorials for now until the release of the V4. I will get back to you in the next couple weeks with some updates.

Hello @krofax, it seems Alex has submitted the outline and if he won't be interested in writing the article after the V4,  I will definitely reach out to you. 

I will keep the issue open for now

**Comment by ShadaW11** [comment]
Hello @oviecodes We are now accepting articles from writers that commit to updating the content of the article after the V4 release. If this is something you can do, kindly let me know and we could proceed with the article.

**Comment by oviecodes** [comment]
Hey @ShadaW11, 

I'm still open to writing the article...
Let me know the next steps.

**Comment by MattieBelt** [comment]
Hey @oviecodes,

I think it is also a good idea to write in short about when not to use the build in `cron` feature and a possible solution for what you could use. For example when having a containerized application with multiple 'horizontal-scaled' Strapi instances.

**Comment by ShadaW11** [comment]
Hey @oviecodes Do you think you could cover what @MattieBelt mentioned?

**Comment by oviecodes** [comment]
Hey @ShadaW11 , I really have no understanding of what @MattieBelt is talking about but if @MattieBelt could elaborate on it maybe I could cover it

**Comment by MattieBelt** [comment]
Yes sure, so Strapi has an build in cron feature, well documented in the configurations docs [here](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#cron-tasks).
And explained in [this (old) guide](https://strapi.io/documentation/developer-docs/latest/guides/scheduled-publication.html) with some more context (e.g. Scheduled publication).

But as the tip in the guide suggests:
> 💡 **TIP**
Please note that Strapi's built in CRON feature will not work if you plan to use pm2 or node based clustering. You will need to execute these CRON tasks outside of Strapi.

Let me try to explain that a bit more. So you could for example deploy your strapi application in multiple containers/clusters/instances, to boost the performance ([horizontal scaling](https://stackoverflow.com/a/11715598)). This could for example be in multiple pm2 clusters or Google App engine instances, depending on the hosting. 

If it is the case that you have deployed your strapi application in multiple instances then each of those will trigger the cron job and then for example you could have duplicate emails sending because it was triggered & executed in more then one instance.

A solution for this could be to use an third party service that handles the scheduling with for example cron and then uses an custom endpoint to trigger (in one instance) the custom code once.

I don't think that the article should include an example, but it should mention/explain at least the concept of how to handle this and provide some third party services that could be used to do this.

Do you have any experience with setting up an scheduled task with multiple instances @oviecodes?
Sorry for my not so clear previous reply. 

@derrickmehaffy Am I missing something here, any simple tips on using cron with multiple Strapi instances?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Am I missing something here, any simple tips on using cron with multiple Strapi instances?

Nope that's exactly it. My usual suggestion is to create a custom route/controller that would perform the same logic as a crontask (maybe implement API tokens to secure it). Then you would call this endpoint from any other system.

Could be the built in cronjob system in Linux with a simple curl request or using a more complex self hosted cron system.

You can even use things like Zapier or IFTTT, doesn't matter what it is so long as it can make the GET, POST, or PUT request you want (usually GET).

This way the "crontask" endpoint will only be executed on one node of the cluster.

**Comment by oviecodes** [comment]
Hey, @MattieBelt I don't have experience with setting up cron jobs with multiple instances. But I do understand your point, when using multiple instances, different instances may invoke the same cron job, hence leading to the job being executed multiple times.
Nice point @derrickmehaffy it's a nice solution, but I don't have much experience working with multiple as I have never built a large-scale application that required horizontal scaling, with your permission I could offer this bit of advice in the tutorial and maybe do some research also.

**Comment by oviecodes** [comment]
Hey, @ShadaW11 do I proceed with this article?

**Comment by ShadaW11** [comment]
This topic is put on hold until the V4 release @oviecodes

**Comment by oviecodes** [comment]
Hey Shada, can I take this now that v4 is out?

**Comment by oviecodes** [comment]
Hey @ShadaW11 , can I take this now that v4 is out?

**Comment by derrickmehaffy** [comment]
> Hey @ShadaW11 , can I take this now that v4 is out?

She is on vacation for the rest of the year but I don't see any issue with that @oviecodes :)

**Comment by ShadaW11** [comment]
@oviecodes yesss, if you have time please go ahead and start working on it

**Comment by oviecodes** [comment]
Okay @ShadaW11

**Comment by oviecodes** [comment]
@ShadaW11 , here's the ink to the article
https://www.dropbox.com/scl/fi/o4spytldth12dwr92jxcn/Automating-Emails-with-Strapi-CRON-Jobs.paper?dl=0&rlkey=osvdra6ujeraz3xw8kybxgtcc

**Comment by TiaraOluwanimi** [comment]
Hello, @oviecodes, I left a comment for you on the doc. Please, attend to it. Thanks

**Comment by oviecodes** [comment]
@TiaraOluwanimi  yeah, I have added the links to the repo

**Comment by oviecodes** [comment]
hello @TiaraOluwanimi please are there any updates on this article?

**Comment by dessireugarte** [comment]
Sorry for the delay @oviecodes 🙏 
You can submit your invoice so @malgamves can give a follow up to the payment

**Comment by PaulBratslavsky** [comment]
Closing since this article is marked as done.
