### ISSUE TITLE
[Change default wysiwyg editor tutorial not working with v4]

### ISSUE THREAD

**Issue by meherchandan** [strapi/community-content#581]
**The concerning content**
Unable to change the wysiwyg editor in strapi v4 using the tutorial. It was working fine with earlier versions.

**Issue**
https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi

**Comment by ShadaW11** [comment]
Hello @meherchandan thank you, we will be updating this content soon.

**Comment by Hannesalm** [comment]
Any news on this? I have the same problem

**Comment by Mcastres** [comment]
Sorry for the delay, unfortunately, this will not be updated until the end of February

**Comment by victor-baumann** [comment]
I started working on a plugin for Strapi V4 since I need it this week, based on the current WYSIWYG plugin in content-manager. Looks like it most of it is very reusable, just replacing CodeMirror with TinyMCE. Have the basics working but still got some issues (more of react knowledge problem on my end than anything with strapi) 

https://github.com/victor-baumann/strapi-v4-tinymce-example

Also started bit of a write-up on how to create this or similar plugins here. But will take a couple of days until I have something more substantial.

https://vbm.io/til/20220110-strapi-v4-wysiwyg-tinymce/

**Comment by Mcastres** [comment]
That looks great @victor-baumann! I will give it a try during the week

**Comment by Mcastres** [comment]
Hello @victor-baumann 👋 
I wanted to give your plugin a try but there is an [error](https://github.com/victor-baumann/strapi-v4-tinymce-example/blob/9eb2e1f979e4bb220f3c585e8f4b5c0c2570a6d3/src/plugins/wysiwyg/admin/src/components/Wysiwyg/index.js#L90). This `TypographyAsterisk` component doesn't exists 🤔

**Comment by ShadaW11** [comment]
Hello everyone, the article has been updated with v4

**Comment by ddoherty** [comment]
> Hello everyone, the article has been updated with v4

This is not true.  The article still contains instructions for v3.
