### ISSUE TITLE
[Request New Content] "Migrating content between environments using Import Export Entries plugin"

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#905]
**My Request**

Request: 
Migrating content between environments using [Import Export Entries plugin](https://market.strapi.io/plugins/strapi-plugin-import-export-entries)

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by EmmanuelTheCoder** [comment]
I'd love to work on this article.

**Comment by EmmanuelTheCoder** [comment]
@PaulBratslavsky @dessireugarte  here's the outline

Outline

* Introduction

* The importance of UID field in content pulling

* Synchronizing environment

* Best practices for migrating content 

* Conclusion

**Comment by dessireugarte** [comment]
Hello @EmmanuelTheCoder 👋 
We reviewed the outline and looks good.
You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x). 
Once your article is ready, please share the link here so @TiaraOluwanimi can review the article.

**Comment by EmmanuelTheCoder** [comment]
Alright, thanks. On it right away.

**Comment by dessireugarte** [comment]
Hello @EmmanuelTheCoder 👋 How are you?
I'd like to know what is the progress in this article? Do you have a draft ready?

**Comment by ibn-ashimi** [comment]
Hi @dessireugarte I will like to take this up

**Comment by ibn-ashimi** [comment]
alright @dessireugarte. sure.

**Comment by dessireugarte** [comment]
Great, then I'm assigning this issue to you. You can get started @ibn-ashimi 👍

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋 
We would like to publish this article between the second and third week of December. We might need at least 10 days to review it. Do you think we can make it on this timeline?

**Comment by ibn-ashimi** [comment]
Yes, I will work towards it.

**Comment by ibn-ashimi** [comment]
Hello @dessireugarte here is my draft https://www.dropbox.com/scl/fi/2c7ptwy83bliggn5hlzt3/Migrating-content-between-environments-using-Import-Export-Entries-plugin.paper?dl=0&rlkey=d42klpmivmkm1ntd608t8bara

**Comment by ibn-ashimi** [comment]
Hello @dessireugarte any update here ?

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋
I left some comments!

**Comment by dessireugarte** [comment]
Hi @ibn-ashimi! 
I think it would be good to include some images or gifs to help the people using the tutorial.

**Comment by ibn-ashimi** [comment]
That's correct @dessireugarte I will do that soon.

**Comment by ibn-ashimi** [comment]
Hello @dessireugarte I updated it with images.

**Comment by malgamves** [comment]
Hello @Ashimi0x  👋 
Your article is [live](https://strapi.io/blog/migrating-content-between-environments-using-import-export-entries-plugin) 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) for $, since the tutorial is _ with <> 1300 words, and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by Ashimi0x** [comment]
Hi @malgamves Any update on this?

**Comment by malgamves** [comment]
hey @Ashimi0x , @dessireugarte will get back to you on this soon.

**Comment by dessireugarte** [comment]
Hello @Ashimi0x! The invoice should be enough since you already filled once the Vendor form. I already submitted your payment, and Finance will process it next Thursday. If there is any problem, I'll reach out.

**Comment by Ashimi0x** [comment]
Hi @dessireugarte Any update on this?

**Comment by dessireugarte** [comment]
Hello @Ashimi0x 👋
Could you please confirm if have already received your payment?
