### ISSUE TITLE
[SUBMIT] 

### ISSUE THREAD

**Issue by Ksound22** [strapi/community-content#929]
**My resource**

# Article Proposal

## Title
How to Make a Random Quote Generator with Strapi and React

## Description
An article on how to make a random quote generator with Strapi and React. 

The quotes will be created with Strapi and React will be used to display the quotes and their authors on the frontend. 

The app will have a button that shares a quote with Twitter. 

## Outline
- Introduction
- Goals of this Article
- Prerequisites - Basic Skills and What you need to Have in Place
- What is Strapi?
- How Can I Get Started with Strapi?
- How to Build the Quotes API
  - How to Create the Collection for the Quotes API
  - How to Add Fields to the Collection
  - How to Add the Content with the Strapi GUI
  - How to Add the Content with Postman
- How to Make the React app
  - How to Create the Navbar Component
  - How to Create the QuoteBody Component
    - How to Make the API Call to get Random Data from the Strapi API
    - How to Create the Share on Twitter Button
    - How to Create the Footer Component
- Final Thoughts

**Comment by PaulBratslavsky** [comment]
@Ksound22 how were you thinking of handling getting a random quote.  I think for showcasing the use of Strapi it will be cool to do in on the Strapi side of thinks via a custom controller and route that will always return a random code rather then handling the logic on the front end.  Is that the way you were thinking of doing this.

**Comment by Ksound22** [comment]
If you have a resource that can help me do it from Strapi, kindly send
it to me.

**Comment by PaulBratslavsky** [comment]
@Ksound22 you can use this as a reference.  

https://docs.strapi.io/developer-docs/latest/development/backend-customization.html 

Instead of having the logic on the front end, you showcased in your previous example you would do something similar inside a controller.

You would.

1.  Create a custom route get-random-quote
2. You would create a custom controller getRandomQuote
      - you would put your logic here
3. Enable the controller that you just created in the settings
4. Then call from the front end

Why don't you give it a try, create a strapi project and try to make a custom route and controller?  If you get stuck, I can help you.

Docs for creating routes https://docs.strapi.io/developer-docs/latest/development/backend-customization/routes.html

Docs for creating a controller https://docs.strapi.io/developer-docs/latest/development/backend-customization/controllers.html

**Comment by Ksound22** [comment]
I will try it today and let you know as things go

**Comment by PaulBratslavsky** [comment]
Nice

**Comment by Ksound22** [comment]
Hey Paul,

I've tried to create the random route but I can't find my way around it. 

How can you help me?

**Comment by Ksound22** [comment]
@PaulBratslavsky how can you help me?

**Comment by Ksound22** [comment]
@PaulBratslavsky how can you help?

**Comment by PaulBratslavsky** [comment]
@Ksound22 can you share the code example and I can help you out?  Do you have your project on GitHub?

**Comment by Ksound22** [comment]
@PaulBratslavsky, here's the link to the repo: https://github.com/Ksound22/strapi-quote-generator

Its public.

**Comment by Ksound22** [comment]
I'll push the project to GitHub soon so I'll be able to share it with you.

**Comment by PaulBratslavsky** [comment]
@Ksound22 sorry for super late response. Here is the update to your code. 

But with that being said at the moment, we are looking for more advanced tutorials for 2023, so for the time being, I will be closing this issue.

``` javascript
const { createCoreController } = require("@strapi/strapi").factories;

module.exports = createCoreController("api::quote.quote", () => ({
  async index(ctx, data, next) {

    // get quote by random number
    const quote = await strapi.entityService.findMany('api::quote.quote');

    // generate random number form array length
    const random = Math.floor(Math.random() * quote.length);

    ctx.send({ data: quote[random] });
  },
}));
 

```
