### ISSUE TITLE
Deploy Strapi to Cloudflare Pages

### ISSUE THREAD

**Issue by sschweimler** [strapi/community-content#955]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ibn-ashimi** [comment]
Hi, @PaulBratslavsky I will like to work on this.

**Comment by sschweimler** [comment]
Hi,

after some research I don‘t think it‘s possible since cloudflare pages is
for static site hosting and strapi is a dynamic web app.

Abdulwahab Ashimi ***@***.***> schrieb am Di. 6. Sept. 2022
um 16:33:

**Comment by PaulBratslavsky** [comment]
@ibn-ashimi and @sschweimler maybe you can host Strapi on some other platform and host your UI on Cloudflare and implement a hook that will redeploy your frontend on cloudflare whenever content in Strapi changes.

**Comment by shammadahmed** [comment]
This is similar to like hosting Ghost on your own desktop with an SSG like Eleventy deployed on Netlify. If Ibn-Ashimi leaves it, choose me second please. I'd like to write it. @PaulBratslavsky

**Comment by dessireugarte** [comment]
Let us know @ibn-ashimi if you are still interested 👍 
Thanks @shammadahmed , we will let you know

**Comment by Bishopukpai** [comment]
Hi please can I write about this topic

**Comment by ibn-ashimi** [comment]
@dessireugarte I am already working on something else. Thank you.

**Comment by shammadahmed** [comment]
Thanks man @ibn-ashimi 

@dessireugarte Please assign it to me and you can add the 'in progress' label to it.

**Comment by PaulBratslavsky** [comment]
@ibn-ashimi since you are working on something else I will assign it to @shammadahmed.

When ever you have an outline, please share it here.  Thank you.

**Comment by ibn-ashimi** [comment]
@shammadahmed Are you on twitter? whats your handle?

**Comment by shammadahmed** [comment]
@PaulBratslavsky Since Heroku is ending the free tier in November, my tutorial will use Render to deploy the backend. Here is the outline:

- Introduction
- Strapi - a headless CMS
- Cloudflare Pages - a JAMstack platform
- Goals
- Prerequisites
- Choose a hosting platform for Strapi
- Deploy the backend
- Add content
- Choose a UI
- Deploy the frontend
- Automatically redeploy with webhooks
- Conclusion

---------

@ibn-ashimi It's the same as here.

**Comment by ibn-ashimi** [comment]
Cool. Followed you @shammadahmed

**Comment by shammadahmed** [comment]
@PaulBratslavsky @dessireugarte I am mostly done with the article, could you guys please confirm the outline first so I can post the link for review?

**Comment by PaulBratslavsky** [comment]
@shammadahmed can you add a section talking about SEO and why it is important, and how JAMstack apps help with that? And in your Strapi app, you can use the SEO plugin and add that metadata in the Cloudflare pages website.

**Comment by shammadahmed** [comment]
@PaulBratslavsky The tutorial has come about pretty solid (about 2700 words). I have used the Strapi starter templates for deployment, with Strapi on Render and Gatsby on Cloudflare Pages. Readers would be able to easily follow step by step to deploy on Cloudflare Pages and connect with webhooks.

My take on the SEO section is that it would block the readers' flow in deploying the site, but I can surely add the section if you guys want.

This is my first article for Strapi and I have worked hard on it. You guys would like it.

**Comment by PaulBratslavsky** [comment]
@shammadahmed ok thanks for the context, we can leave out the above-mentioned recommendation around SEO.  When ready can submit the draft for review.🙂

**Comment by shammadahmed** [comment]
@PaulBratslavsky Awesome man. The draft is ready, I just need to add keywords, and proofread it. 

About that SEO topic: I was reading about SEO and JAMstack yesterday. I found it very interesting how JAMstack makes very search-friendly websites possible since crawlers like static sites. I would love to write a article/tutorial on it covering everything from the theory to the Strapi SEO plugin. What are your thoughts?

**Comment by shammadahmed** [comment]
@PaulBratslavsky @TiaraOluwanimi It is ready, hope you guys like it: https://www.dropbox.com/scl/fi/9u4chsqq7q8ujqf7hywlt/How-to-Deploy-Strapi-on-Cloudflare-Pages.paper?dl=0&rlkey=hrf5ta2hqmtj9g5r5g2ebh58r

@dessireugarte It is labeled 'article', though it is a tutorial.

**Comment by dessireugarte** [comment]
Thanks @shammadahmed 👋 We will review the draft. I'll get back to you.

**Comment by dessireugarte** [comment]
Hello @shammadahmed 👋
Just wanted to let you know that your article will be published around the first week of December. I'll let you know if we need any changes or when it is published!

**Comment by shammadahmed** [comment]
@dessireugarte This is very good news. Thank you for your guys' part. I am looking forward to when it gets live.

**Comment by balupton** [comment]
Stumbled upon this looking for a way to run Strapi on Cloudflare Pages, rather than just deploying Strapi content to Cloudflare Pages.

Its a common misconception that Cloudflare Pages is static content only, however that is not the case. Cloudflare Pages is some tooling atop of Cloudflare Workers + KV to offer edge based serving of static and dynamic content, akin to Vercel's deployment platform, but with all the benefits of Cloudflare: cdn, ddos protection, workers, kv, d1, r2, queue, stream, access, warp, argo, etc. Where Vercel has Next, Cloudflare has Remix and Astro.

Personally, I'm planning to build a few Remix apps and Astro websites that use Strapi for its access to KV, D1, and R2.

**Comment by PaulBratslavsky** [comment]
@shammadahmed I added some minor comments in your draft, let me know if they make sense or if you have questions.

**Comment by shammadahmed** [comment]
@PaulBratslavsky Thanks for the review man.

Advanced tab env variables & Render memory limit: I think you have missed the block quotes while reading: I mention the solution for both the environment variables error and Render free plan memory limit issues. 

API Token: I left the token generation part for later so the article achieves a chronological flow so the reader can deploy the template quickly to production in one go. But if you say, I can explain it there as well or just add an in-article link to that part there.

Let me know if I misunderstood any of the comments.

**Comment by dessireugarte** [comment]
Hello @shammadahmed  👋 
Your article is [live](https://strapi.io/blog/how-to-deploy-strapi-on-cloudflare-pages)! 🎉 Great job!
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also, please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!
