### ISSUE TITLE
strapi starter[TOPIC]

### ISSUE THREAD

**Issue by jcnew777** [strapi/community-content#986]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by eunice-ogboye** [comment]
I like to write on thi topic

**Comment by PaulBratslavsky** [comment]
We have many articles in the queue and are only accepting new articles in January of next year. 

I will be closing this topic for now, since we are currently building a new starter template with Next JS 13 and Strapi. Will let you know when it is updated.

We also have decided to focus our efforts on producing higher-quality content for our readers.

Also, we will be introducing new tags by level beginner, intermediate, and advanced.   As well as update the rate to encourage our writers to write about more intermediate/advanced Strapi content.

We are working on redoing WFC guidelines to reflect these changes and providing some common topics that our community and members request.

If you have any questions, feel free to reach out to me on Discord in the WFC community channel.
