### ISSUE TITLE
[SUBMIT] ARM Template with an autodeploy script for Azure IaaS

### ISSUE THREAD

**Issue by sangramrath** [strapi/community-content#995]
**My resource**

My proposal is to provide an ARM template for Azure IaaS deployment (VM with all components running on the same VM i.e. strapi & mysql) along with a bash script which can be supplied as user-data during Azure VM provisioning that installs Strapi and provides a live deployment that can be quick accessed.

This would be good for anyone just wanting to quickly get started without having to go through the app build and configuration process. 

The article will have:
- General steps to follow
- An ARM template which deploys without any intervention or customization (Deploy to Azure button)
- Optional steps / process to make customization if needed

It can be added to existing Azure IaaS document section or it can be a new document. 

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

I have most of the template / code ready, and can complete the rest on assignment of the issue.

**What do you all think?**
❤️ I love it!

**Comment by sangramrath** [comment]
@dessireugarte @PaulBratslavsky I have some scripts that are used as part of my article. Would it be preferred that they are in strapi's community repo? 

If yes, I assume I fork and raise a PR for the scripts. Is that right?

**Comment by sangramrath** [comment]
@PaulBratslavsky / @dessireugarte the article can be reviewed at https://www.dropbox.com/scl/fi/0mr59fh8xaqp4v67uu2ag/Strapi-quickstart-with-Azure-ARM-templates.paper?dl=0&rlkey=wpcdc7qto0xas6qee3rxh633i.

**Comment by dessireugarte** [comment]
Hello @sangramrath 👋
Thanks for submitting your draft. We will review it, and if we need changes, we will contact you, otherwise, we will publish this between the first and second week of January.

**Comment by sangramrath** [comment]
Thank You @dessireugarte, there is another request (issue) I submitted too. It would be great to know if there's a go ahead on that.

**Comment by dessireugarte** [comment]
Hello @sangramrath 👋
As I notified you previously, we will publish it in January. We will let you know if we need changes to be done. But in the meantime, could you please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice? 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform). Since this article is still not published, please add the link of the draft. Please make this before **January 2nd**.

**Comment by sangramrath** [comment]
Hi @dessireugarte, thanks. 
The forms have been submitted.

**Comment by PaulBratslavsky** [comment]
@sangramrath I was reviewing the article, I am new to Azure, wanted to test the deployed strapi app but not sure where to look.  I had a public address that i tried `http://strapi-rlqyj.eastus.cloudapp.azure.com/` but this does not work.  Just trying to figure out what I am missing. Thanks.

**Comment by sangramrath** [comment]
@PaulBratslavsky I also have another tutorial in mind around Azure ARM templates (code already written) on deploying Strapi to Azure PaaS services such as Azure App Service + Azure DB for MySQL with the Azure Storage provider. I saw a few forum posts around this, so let me know if this would be something the team would be interested in.

**Comment by PaulBratslavsky** [comment]
@sangramrath thank you for the help 😀  @dessireugarte this is ready to be published.

**Comment by sangramrath** [comment]
Thank You @dessireugarte, the article has a "deploy to azure" button that's not working (it's not clickable and appears as an image only). So that needs corrected (it works in the Dropbox draft link).
