### ISSUE TITLE
[SUBMIT]Create a Book Rating Application With Strapi Ratings Plugin and Cloudinary

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#998]
# Introduction
Imagine having a book rating application where users can go to see the review of any book together with their opinions on the book. In this project, we will create a book rating application using the Strapi Ratings Plugin for ratings, and Cloudinary for image upload.

## Outline
1. Introduction
2. Setup
3. Strapi Ratings Plugin and Installation
4. Cloudinary installation and connection.
5. Create Book Content Type
6. implementing the frontend
7. Adding a WYSIWYG editor Quill
8. connecting our application
9. customizing the backend controller 
10. conclusion

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku can you tell me more about what customizations you will make in the controller? We are currently looking for more articles that cover more topics around customizations.  

I still like your idea. But I feel that the main key topic would be to focus on interesting ways to customize the controller and possibly add a policy or a middleware.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky. Very true, the interesting way the controller, middleware, and policy would be customized include: 

The controller customizations include:
1. Add New Controllers (for instance a likeBook controller which will handle likes for a book). Plus it will also come with a customized route. Also, a controller for admin to delete a book that comes with its own route and middleware.
2. Extend Core controllers create, update, and delete. 
3. Enable authorization in the form of authorizing who owns a book and who can delete or edit it. 

Adding Middlewares for:
1. Adding authorization middleware before any controller is called. 
2. Adding strapi/provider-upload-cloudinary security middleware
3. Customizing middleware for Strapi Node-formidable library 

Adding Policy for Admin:
1. Only an admin can delete any user’s post (for moderation)

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku nice you can get started on this.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky,
Hi @dessireugarte 

Thanks for this opportunity. I really enjoyed writing and building this. 😊

Here is my first draft. 

Thanks. Here is the link to the tutorial:
https://www.dropbox.com/scl/fi/e7gts5f4dnfa5f2qwgdkk/Create-a-Book-Rating-App-with-Strapi-Ratings-Plugin-and-Cloudinary.paper?dl=0&rlkey=kmyy2l98rqzpetwt6gig19c94

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky.
Hi @dessireugarte, 

I sure hope you are doing great!
Please I have not gotten any response on my submitted draft. 

Thanks

**Comment by dessireugarte** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku 👋
Thanks for submitting the draft. This article is already in the process of being reviewed, and we will get back to you in case we need changes. Otherwise, we will post it between the last week of December and the first week of January.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
That will be nice @dessireugarte  😊.

Thanks.

**Comment by dessireugarte** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku 👋
As I notified you previously, we will publish it in January. We will let you know if we need changes to be done. But in the meantime, could you please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice? 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform). Since this article is still not published, please add the link of the draft. Please make this before **January 2nd**.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @dessireugarte , thanks for your time, I am grateful. Compliments of the season!

I have done the tasks above by filling out the W-8BEN form, and "individual form" vendor form,  created an invoice, and have also submitted the invoice. 

Thanks once again.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @dessireugarte,
I sure hope you are doing fine.

Just a reminder. I guess my article publication won't be in this first week of January as you said earlier?

Anyways, I am glad my article has been reviewed by @PaulBratslavsky 💪.

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku  this has been scheduled to be published will let you know when it is live.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
@PaulBratslavsky Great!

**Comment by malgamves** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku 👋 

Your article is [live](https://strapi.io/blog/create-a-book-rating-app-with-strapi-ratings-plugin-and-cloudinary)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) for $, since the tutorial is _ with <> 1300 words, and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Great! @malgamves. Thanks. I am so much happy 😊



PS: Please I thought this was intermediate. Is there a reason why it is labeled "intermediate" here and "beginner" on Strapi blog?
@PaulBratslavsky @dessireugarte

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
It's fixed now 🥳.

Thanks a million times @dessireugarte @PaulBratslavsky @malgamves

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Can you please fix the typo on the title of the article?

It's missing the word "To".

"How Create a Book Rating App with Strapi Ratings Plugin and Cloudinary"

 Should be:
"How To Create a Book Rating App with Strapi Ratings Plugin and Cloudinary"

Thanks @malgamves

**Comment by malgamves** [comment]
done, great catch @Theodore-Kelechukwu-Onyejiaku

**Comment by PaulBratslavsky** [comment]
Since this article is marked as done I will he closing this issue.  Thank you @Theodore-Kelechukwu-Onyejiaku for writing the article.
